version: '3.8'
services:
  app:
    build: .
    labels:
      - "com.docker.order.version=1.0.0"
      - "com.docker.order.dockerfile.date=15.10.2020"
    ports:
      - "8080:8080"
    volumes:
      - vol_test:/app
#  front:
#    build: ./
#    labels:
#      - "com.docker.order.front.version=1.0.0"
#    ports:
#      - "4200:4200"

volumes:
  vol_test:

